#!/usr/bin/env python3
import os, sys, warnings
from types import ModuleType
from importlib import import_module

path = os.path.abspath(os.path.dirname(__file__))
format = "." + ("eps" if len(sys.argv) == 1 else sys.argv[1])

def build():
    for f in os.listdir(os.path.join(path, "plots")):
        if f.endswith(".py") and f != "__init__.py":
            plot = import_module("." + f[:-3], package="plots")
            plot.__figname__ = f[:-3]
            build_figure(plot)

def build_figure(plotting_module):
    fig = plotting_module.plot()
    fig.write_image(os.path.join(
        path, "figures", plotting_module.__figname__ + format
    ), width=1920, height=1080)

if __name__ == "__main__":
    build()
